name: .rc tag release

on:
  push:
    tags:
      - v\d+\.\d+\.\d+
    tags-ignore:
      - v*\.*\.*-rc
      - v*\.*\.*-rc\.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: tag release pro success
        run: |
          echo 'release pro success'
