name: .rc tag release

on:
  push:
    tags:
      - v*\.*\.*-rc
      - v*\.*\.*-rc\.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: tag release success
        run: |
          echo 'release success'
