name: Trigger on comment

on:
  issue_comment:
    types:
      - created

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get BRANCH_NAME
        if: >-
          github.event_name == 'issue_comment'
          && github.event.issue.number != ''
          && contains(github.event.comment.body, '/deploy-pms')
        run: echo Hello, world!
